# Generated by Django 2.2.6 on 2019-10-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191031_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='content',
            new_name='age',
        ),
    ]
