# Generated by Django 2.2.6 on 2019-10-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('lecture', models.CharField(max_length=20)),
                ('professor', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('dayofwekk', models.CharField(max_length=10)),
            ],
        ),
    ]
