# Generated by Django 2.2.6 on 2019-10-31 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191031_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Myapp',
            new_name='timetable',
        ),
    ]
